- hosts: terraform-ansible
  tasks:
  - name: Installing python3 and virtualenv
    apt:
      pkg:
        - python3
        - virtualenv
      update_cache: yes
    become: yes
  - name: Installing dependencies
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
      - django
      - djangorestframework
    