- hosts: terraform-ansible
  tasks:
  - name: Creating the index.html file
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Made with Terraform and Ansible</h1>
  - name: Creating the HTTP server
    shell: "nohup busybox httpd -f -p 8080 &"